# Generated by Django 5.0.4 on 2025-03-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
    ]
