# Generated by Django 5.0.4 on 2025-03-08 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0007_rename_name_subject_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMSapp.classst'),
        ),
    ]
