# Generated by Django 5.0.4 on 2025-03-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0009_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigned',
            name='subject',
        ),
        migrations.AddField(
            model_name='assigned',
            name='subject',
            field=models.ManyToManyField(blank=True, to='LMSapp.subject'),
        ),
    ]
