# Generated by Django 5.0.4 on 2025-03-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0012_remove_staff_class_assigned_staff_class_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='LMSapp.subject'),
        ),
    ]
