# Generated by Django 5.0.4 on 2025-03-12 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0013_remove_staff_subject_staff_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='class_assigned',
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject',
            field=models.ManyToManyField(blank=True, to='LMSapp.subject'),
        ),
        migrations.AddField(
            model_name='staff',
            name='class_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LMSapp.classst'),
        ),
    ]
