# Generated by Django 5.0.4 on 2025-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMSapp', '0016_student_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
